### PR TITLE
Allow jobs to define their own failure handling

### PR DESCRIPTION
**Pull request by greysteil**
Currently, you can define a global `Que::Failue.on_unhandled_failure` method. This PR allows each job to override that, if it wants to.

### CODE REVIEW

**Comment by greysteil** [comment]
@Sinjo - can you review? I've also heavily refactored the specs.

**Comment by Sinjo** [comment]
I'd really like to tackle https://trello.com/c/9hQ63ltX/67-replicate-rails-s-per-connection-set-statements-in-pgbouncer-s-connect-query today, and I'm out tomorrow. Is this causing major headaches, or can I review it on Monday instead?

**Comment by greysteil** [comment]
Monday is fine!

**Comment by Sinjo** [comment]
Thanks!

**Comment by Sinjo** [comment]
:+1: on the approach. Do you have a couple of motivating examples for overriding these callbacks in specific workers? In the general case it's nice to know that we'll get the log/Sentry for retryable/unhandled failures respectively.

I'm open to allowing specific workers to override, but I'd like to know what for.

Didn't manage to read the test code today. Will do that tomorrow morning!

**Comment by greysteil** [comment]
I was originally thinking of putting some logic into the `on_unhandled_failure` category for AML checks (in some cases we want to complain loudly, in others we want to fail silently). Appreciate that could go into the body of the job, but at the time handling it in the above method felt clearer.

I can also see a case for customising `on_retryable_failure` for a class of jobs - for some we might want to send a warning email, whereas for others we might want to send the issue to Sentry.

**Comment by Sinjo** [comment]
> in others we want to fail silently

But what happens to the job in this case? Looking at this worker, it uses the `VariableRetry` strategy. If it stays in the queue (non-retryable), we'll get an audit alert. Is the aim to stop retrying at all on certain failures?

> whereas for others we might want to send the issue to Sentry

It seems quite extreme to Sentry for things which are going to be retried. Concrete examples would be useful here. My first guess is that what we really want is some sort of time bound on certain things happening, or some sort of metric for time spent in the queue, but it's hard to say without examples.

**Comment by greysteil** [comment]
Sorry, on the retry one I meant that in some cases we might want to send a warning email whilst on others we might want to quietly retry. The stuff we're doing with submission audit emails is a good example - we want to send an email alerting that things are still messed up, and then retry the audit in a little while.

**Comment by greysteil** [comment]
@Sinjo - can you take a look at this today if you get a chance?

**Comment by Sinjo** [comment]
Used sparingly, and only in cases where we want to change the level of alert we received, I can see this being okay. My worries are:

- It'll be seen as convenient, and get overused for other things.
- The code overriding the failure handling needs to remember to re-raise exceptions that it doesn't want custom behaviour for. In this regard, rescuing in `perform` has much nicer behaviour. The same is true for logging of retryable failures, though a little less worrying.

**Comment by greysteil** [comment]
Makes sense - closing, and I'll put the spec refactor into a separate PR.

**Pull request closed without merging**
