### PR TITLE
Use the exception .=== method to detect error types

### PR DESCRIPTION
**Pull request by nickcampbell18**
Internally, when you do this:

```
  begin
    raise ArgumentError, "Foo"
  rescue ArgumentError => e
    ...
  end
```

Ruby is [actually doing the rescue check like this](https://blog.honeybadger.io/ruby-rescue-elegant-trick-for-knowing-which-exceptions-to-catch/):

```
  ArgumentError === e
```

This has subtle differences to `#is_a?`, which was how we previously implemented this same check. This commit uses the triple equality method to be consistent with normal exception behaviour.

The issue which caused this commit occurred with Faraday, which has an exception class visible in two namespaces:

```
  Faraday::ConnectionFailed
  Faraday::Error::ConnectionFailed
```

We can rescue one of these two and `===` will correctly identify this exception in both of those cases.

### CODE REVIEW

**Comment by nickcampbell18** [comment]
Merging blocked by https://gocardless.myjetbrains.com/youtrack/issue/PT-2211

**Comment by nickcampbell18** [comment]
Also, I wasn't sure whether to write a spec for this. It's really just an internal implementation consistency problem - a spec implies that it might have been a feature change... as a standalone, that spec would be a bit weird I reckon.

**Comment by cristiangreco** [comment]
@nickcampbell18 TIL about `===` and the group defined by an expression.

However, I'm not totally sure how this change fixes the original problem. I think I'm missing something?

```rb
> Faraday::ConnectionFailed === Faraday::Error::ConnectionFailed
=> false
```

**Comment by nickcampbell18** [comment]
@cristiangreco almost - its called from a class to an instance:

```
Faraday::Error::ConnectionFailed === Faraday::ConnectionFailed.new("whatever")
=> true
```

**Comment by cristiangreco** [comment]
This is getting more and more interesting:

```rb
irb(main):014:0> Faraday::ConnectionFailed.new("123") === Faraday::Error::ConnectionFailed
=> false
irb(main):015:0> Faraday::Error::ConnectionFailed === Faraday::ConnectionFailed.new("123")
=> true
irb(main):016:0> Faraday::ConnectionFailed.new("123").is_a?(Faraday::Error::ConnectionFailed)
=> true
```

**Comment by nickcampbell18** [comment]
Thanks both! In writing a spec I realised that `is_a?(..)` is actually working correctly and I was chasing a red herring.

Back to the drawing board.

**Pull request closed without merging**
